server:
  port: 8080
spring:
  application:
    name: todo-items
  datasource:
    url: jdbc:h2:mem:todo-db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update