server:
  port: 8080

spring:
  application:
    name: todo-items

  datasource:
    url: jdbc:h2:mem:todo-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

expiry:
  check:
    interval: 0 */1 * ? * *
